export interface Movie {
    id: string
    title: string
    title_other: string
    release_date: string
    description: string
    vertical_poster: string
    horizontal_poster: string
    genres: string[]
    trailer_url: string
    age: number
    views_count: number
    rating: number
    year: number
    country: string
    quality: string
    duration_minutes: number
    actors: string[]
    directors: string[]
    category: string
    comments_count: number
    film_url?: string
    watch_duration_minutes: number
    watched_at: string
    rank: number
    tags?: string[]
    created_at: string
    updated_at: string
    like_count: number
    share_count: number
    isVip: boolean
}
