import type { Metadata } from 'next'
import './globals.css'
import { hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { setRequestLocale } from 'next-intl/server'
import { NetflixIcons, NetflixSans } from '@/config/fonts.config'
import { NextIntlClientProvider } from 'next-intl'
import { AppProvider } from '@/provider/app-provider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode
    params: Promise<{ locale: string }>
}>) {
    const { locale } = await params
    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    setRequestLocale(locale)

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={`${NetflixSans.variable} ${NetflixIcons.variable} antialiased`}>
                <NextIntlClientProvider>
                    <AppProvider>{children}</AppProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
